### ISSUE TITLE
Thread count exceeded when saving debug images

### ISSUE THREAD

**Issue by JackBuck** [JackBuck/Robo-Plot#157]
When following many curves, as in challenge 2, the plotter tries to save lots and lots of debug images. Each save call is placed on a separate thread, and because the plotter can't save that much information fast enough to end the threads, the maximum thread count is being exceeded.

Proposed solution:
  - Have a single thread to save all the photos one by one, implementing a fifo queuing system for photos to save
  - Photos designated to be saved with the same name as an existing photo should replace that photo in the queue (maybe bumping it back to the end of the queue?)
  - If the queue runs out of space, discard the first placed item (i.e. the next in line) without saving it. Then add the new image to the end of the queue in the newly created space.

**Comment by JackBuck** [comment]
For reference, my computer bombs out when trying to create thread 149:

```
import threading
import time


def count_threads(threads):
    """
    Args:
        threads (list[threading.Thread]):
    """
    return len([t for t in threads if t.is_alive()])


threads = []
for i in range(1000):
    t = threading.Thread(target=lambda: time.sleep(1))
    threads.append(t)
    try:
        t.start()
    except RuntimeError:
        print('Failed to create thread: {}'.format(i))
        raise

print(count_threads(threads))
time.sleep(0.5)
print(count_threads(threads))
time.sleep(0.5)
print(count_threads(threads))
```
Output (with redacted file paths):

 ```
Failed to create thread: 149
Traceback (most recent call last):
  File ".../scripts/scratch.py", line 18, in <module>
    t.start()
  File "/usr/lib64/python3.4/threading.py", line 841, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

Process finished with exit code 1
```
